modLoader="javafml"
loaderVersion="[36,)"
license="ARR"
issueTrackerURL="https://github.com/ThDilos/ThDilos.Fox.Origin/issues"
description='''
ThDilos' moderatedly complicated homebrew Fox Origin, with 30% pouncin and 70% foxes :3
'''

[[mods]]
modId="thorigins"
version="4.1.2"
displayName="ThDilos Fox Origins"

[[dependencies.thorigins]]
modId="origins"
mandatory=true
versionRange="[1.12.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins]]
modId="minecraft"
mandatory=true
versionRange="[1.21,)"
ordering="NONE"
side="BOTH"

[[dependencies.thorigins]]
modId="pehkui"
mandatory=true
versionRange="[3.3.3,)"
ordering="NONE"
side="BOTH"